# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

fib = []
a, b, c = 1, 1, 0
fib << a 
fib << b
top = 4_000_000	
while c < top 
	c = a + b
	a = b
	b = c
	fib << c
end

sum = 0
fib.each { |i| 
	(i % 2 == 0) ? sum += i : sum
}
puts sum
		